name: "CI / CD"

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - closed
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: "install npm@latest"
        run: npm i -g npm@latest

      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "run tests"
        run: npm run test --if-present

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: "install npm@latest"
        run: npm i -g npm@latest

      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "lint code"
        run: npm run lint --if-present
