name: "Publish to Digital Ocean"

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/cicd.yml

    - name: "checkout repository"
      uses: actions/checkout@v3

    - name: "install doctl"
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: "build and deploy docker image"
      uses: ripplr-io/docr-docker-publish@v1
      with:
        image_path: registry.digitalocean.com/dev-2ehuyma3n35v/multiweek-plan-generator
