name: "Publish to Digital Ocean"

on:
  workflow_dispatch:

jobs:
  cicd:
    uses: AviSantoso/multiweek-plan-generator/.github/workflows/cicd.yml@main

  publish:
    needs: cicd
    runs-on: ubuntu-latest
    steps:

    - name: "checkout repository"
      uses: actions/checkout@v3

    - name: "install doctl"
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: "build and deploy docker image"
      uses: ripplr-io/docr-docker-publish@v1
      with:
        image_path: dev-2ehuyma3n35v/multiweek-plan-generator
